# Generated by Django 4.2.2 on 2023-07-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_customer_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='name',
            new_name='Cust_name',
        ),
    ]
