# Generated by Django 4.2.2 on 2023-07-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_rename_name_customer_details_cust_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='Cust_name',
            new_name='customer_name',
        ),
    ]
