# Generated by Django 4.2.2 on 2023-07-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_ordermaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping_Details',
        ),
    ]
