# Generated by Django 4.2.2 on 2023-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_mycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userCardNo',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
