# Generated by Django 4.2.2 on 2023-07-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_shipping_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping_Details',
        ),
    ]
