# Generated by Django 4.2.2 on 2023-07-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_delete_shipping_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'Customer_Details',
            },
        ),
    ]
