# Generated by Django 4.2.2 on 2023-07-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_shipping_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_details',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
